Modify AddTransactionModal and add transactionData to HistoryPieChart
ryo-wens/kakeibo-front pull request #286
Opened 2020-12-13 06:32 UTC by ryo-wens

- `Login, Signup`にユーザーIDと名前の入力時にスペースがあった場合にメッセージを表示するバリデーションを追加しました。

- カテゴリーごとの支出額の割合を表示する`HistoryPieChart`で表示させるデーターを`transactions / selectors`に追加しました。

- 仮のデータを表示させていた`HistoryPieChart`にカテゴリーごとに支出額をまとめた`sortTransactionsList`を追加しました。

確認よろしくお願いします。

2020-12-13 07:01 UTC, toshi1127 commented on src/components/home/HistoryPieChart.tsx
> +      for (const transaction of props.sortTransactionsList) {
reduceで足して行ってもいいかもですね

2020-12-13 07:01 UTC, toshi1127 commented on src/components/home/HistoryPieChart.tsx
> +        nameKey={'big_category_name'}
文字列はこう書きますか
nameKey="big_category_name"

2020-12-13 07:41 UTC, ryo-wens commented on src/components/uikit/AddTransactionModal.tsx
> +  const signal = axios.CancelToken.source();
こちらに処理を書いています。
https://github.com/ryo-wens/kakeibo-front/blob/75a2e7a8e1af3083b7af2c158eaaef522d600ab6/src/components/uikit/AddTransactionModal.tsx#L112

2020-12-13 07:41 UTC, ryo-wens commented on src/templates/Home.tsx
> +  const selector = useSelector((state: State) => state);
こちら`getSortCategoryTransactions, getSortCategoryGroupTransactions`を取得する際に使用しています。

2020-12-13 07:41 UTC, ryo-wens commented on src/components/home/HistoryPieChart.tsx
> +        nameKey={'big_category_name'}
prettierの設定で`"singleQuote": true`に設定しており保存時にsingleQuoteになってしまうのですが使い分けを
行った方が良いのでしょうか？

2020-12-13 08:01 UTC, toshi1127 commented on src/templates/Home.tsx
> +  const selector = useSelector((state: State) => state);
なるほど、このように書けますよ！
```
import React from 'react'
import { useSelector } from 'react-redux'
import { createSelector } from 'reselect'

const selectNumOfDoneTodos = createSelector(
  (state) => state.todos,
  (todos) => todos.filter((todo) => todo.isDone).length
)

export const DoneTodosCounter = () => {
  const numOfDoneTodos = useSelector(selectNumOfDoneTodos)
  return <div>{numOfDoneTodos}</div>
}

export const App = () => {
  return (
    <>
      <span>Number of done todos:</span>
      <DoneTodosCounter />
    </>
  )
}
```

2020-12-13 08:02 UTC, toshi1127 commented on src/templates/Home.tsx
> +  const selector = useSelector((state: State) => state);
https://react-redux.js.org/next/api/hooks#using-memoizing-selectors

2020-12-13 08:07 UTC, toshi1127 commented on src/components/home/HistoryPieChart.tsx
> +        nameKey={'big_category_name'}
```
<MyComponent message="hello world" />

<MyComponent message={'hello world'} />
```

https://ja.reactjs.org/docs/jsx-in-depth.html#string-literals
評価のされ方は同じなのですが、静的な文字列は`message="hello world"`みたいに指定することが多いですね！（ドキュメントでもこうなっていることが多いはず

2020-12-13 08:16 UTC, ryo-wens commented on src/components/home/HistoryPieChart.tsx
> +        nameKey={'big_category_name'}
参考記事ありがとうございます！
修正します！

2020-12-13 08:21 UTC, toshi1127 commented on src/components/uikit/AddTransactionModal.tsx
> +  const signal = axios.CancelToken.source();
```
function useFetch(fetcher) => {
  useEffect(() => {
    const signal = axios.CancelToken.source();

    dispatch(fetcher);
    return () => signal.cancel();
  }, []);
}
```
こんな感じで切り出せると綺麗かもですね

2020-12-13 08:55 UTC, ryo-wens commented on src/components/home/HistoryPieChart.tsx
> +      for (const transaction of props.sortTransactionsList) {
selectorで行う形に修正します。

2020-12-13 08:56 UTC, ryo-wens commented on src/components/home/HistoryPieChart.tsx
> +    if (pathName !== 'group') {
if, elseに修正します。

2020-12-13 09:37 UTC, ryo-wens commented
6626235

コメント頂いた部分の修正を行いました。
確認よろしくお願いします！

2020-12-13 09:45 UTC, toshi1127 requested changes

2020-12-13 09:45 UTC, toshi1127 commented on src/components/home/HistoryPieChart.tsx
> +              ? '今月の総支出' + '\n' + '￥' + props.thisMonthTotalExpense.toLocaleString()
テンプレートリテラルを使っていきましょう
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Template_literals

2020-12-13 09:45 UTC, toshi1127 commented on src/reducks/transactions/selectors.ts
> +      .reduce((acc, transaction) => {
この部分重複しているので、切り出しても良いかもです(流石にもう一個同様のロジックが出てきたら、切り出したい

2020-12-13 09:45 UTC, toshi1127 commented on src/templates/Home.tsx
>    const pathName = getPathTemplateName(window.location.pathname);
今ってReact-Routerとか使ってないんでしたっけ？？
https://reactrouter.com/web/api/Hooks/useparams

2020-12-13 09:45 UTC, toshi1127 commented on src/templates/LogIn.tsx
> +                placeholder={''}
placeholder空なのに書く必要ありますかね？

2020-12-13 09:45 UTC, toshi1127 commented on src/templates/SignUp.tsx
> +                placeholder={'スペースを空けずに入力してください'}
ここ修正もれていそう

2020-12-13 10:55 UTC, ryo-wens commented on src/templates/LogIn.tsx
> +                placeholder={''}
propsで受け取る形にしていたので表示させない部分には空文字を渡していました。

2020-12-13 11:24 UTC, ryo-wens commented on src/templates/Home.tsx
>    const pathName = getPathTemplateName(window.location.pathname);
各コンポーネントで`useLocation`を使用するのではなくpaths.tsに切り出した`getPathTemplateName`を使い回す形が
再利用できると思ったのですが`useLocation`を使用した方が良いのでしょうか？

2020-12-13 13:19 UTC, toshi1127 commented on src/templates/Home.tsx
>    const pathName = getPathTemplateName(window.location.pathname);
そうですね
自分たちでメンテしたくないので....

2020-12-13 13:20 UTC, toshi1127 commented on src/templates/LogIn.tsx
> +                placeholder={''}
placeholderが空ってデフォルト値なので、あえて明示的に指定する必要ないと思います
めんどくさくなければ一旦OKです！

2020-12-13 13:42 UTC, ryo-wens commented on src/templates/LogIn.tsx
> +                placeholder={''}
了解しました！

2020-12-13 13:43 UTC, ryo-wens commented on src/templates/Home.tsx
>    const pathName = getPathTemplateName(window.location.pathname);
了解しました！
修正します！

2020-12-13 15:03 UTC, ryo-wens commented
3daa85f

コメント頂いた部分の修正を行いました！
確認よろしくお願いします！

2020-12-13 16:17 UTC, ryo-wens commented
40477af

groupIdの修正を行いました！
確認よろしくお願いします！

2020-12-14 19:00 UTC, toshi1127 approved these changes

2020-12-14 19:45 UTC, merged