Add last month expenses to budgets and groupBudgets
ryo-wens/kakeibo-front pull request #294
Opened 2020-12-24 07:23 UTC by ryo-wens

- 各カテゴリー事の予算の設定を行う`StandardBudgets, GroupStandardBudgets, CustomBudgets, GroupCustomBudgets`に
  先月の支出を見て予算設定を行えるように各カテゴリーの先月の支出`last_month_expenses `を追加しました。

- 先月の支出追加に伴ってテストの修正を行いました。

- `transactions / selectors, groupTransactions / selectors`にStandardBudgetsとCustomBudgetsの総予算を追加しました。

- `StandardBudgets, GroupStandardBudgets, CustomBudgets, GroupCustomBudgets`に使用していたmaterial-uiを削除し
  HTMLタグに変更しました。

確認よろしくお願いします。

2020-12-24 08:18 UTC, toshi1127 requested changes

2020-12-24 08:18 UTC, toshi1127 commented on src/templates/EditStandardBudgets.tsx
> +        {(() => {
jsxの中で即時関数使うのやめますか

2020-12-24 08:18 UTC, toshi1127 commented on src/templates/EditStandardBudgets.tsx
> -          <h1>{pathName !== 'group' ? yearsInPersonal : yearsInGroup}</h1>
いろんなコンポーネントがpathに依存しちゃってるのよくないので直したいですね(余力あれば

2020-12-24 08:18 UTC, toshi1127 commented on src/templates/EditStandardBudgets.tsx
> +                        const onChangeBudget = (event: { target: { value: string } }) => {
引数の部分、自前の型定義する必要ないですかね

2020-12-24 08:18 UTC, toshi1127 commented on src/templates/EditStandardBudgets.tsx
> +                          newBudgets[index].budget = (event.target.value as unknown) as number;
新しくnewbudgets作らなくてもmapのやつ使えばいけそうです？

2020-12-24 08:18 UTC, toshi1127 commented on src/templates/EditStandardBudgets.tsx
>                                rest = {
ここ再代入する必要ありますか？

2020-12-24 08:18 UTC, toshi1127 commented
先にレビューし合ってから依頼いただけるとありがたいです〜！

2020-12-25 06:31 UTC, ryo-wens commented
74e673d

Add group user color for GroupMonthlyHistory #290 の修正を行いました。
確認よろしくお願いします。

2020-12-25 06:57 UTC, ryo-wens commented on src/templates/EditStandardBudgets.tsx
> +                          newBudgets[index].budget = (event.target.value as unknown) as number;
customBudgetsを使った場合、<TextField>でbudgetsの値を変更することができなくなってしまいます。

2020-12-25 07:33 UTC, ryo-wens commented on src/templates/EditStandardBudgets.tsx
> -          <h1>{pathName !== 'group' ? yearsInPersonal : yearsInGroup}</h1>
一旦このまま進めて全体のテンプレートの修正の際に改めてpathの依存を修正したいと思います。

2020-12-25 07:41 UTC, ryo-wens commented on src/templates/EditStandardBudgets.tsx
>                                rest = {
` return {
                            big_category_id: rest.big_category_id,
                            budget: Number(rest.budget),
                          };`に修正します。

2020-12-25 08:08 UTC, ryo-wens commented on src/templates/EditStandardBudgets.tsx
> +                        const onChangeBudget = (event: { target: { value: string } }) => {
eventの型定義を行わない場合、 `newBudgets[index].budget =`の部分で型エラーが出てしまうので引数の部分で定義しています。

2020-12-25 08:09 UTC, ryo-wens commented on src/templates/EditStandardBudgets.tsx
> +        {(() => {
三項演算子を使用する形に修正したいと思います。

2020-12-25 08:50 UTC, ryo-wens commented
317d64
Add last month expenses to budgets and groupBudgets #294 の修正を行いました。

- budgetsをコピーしnewBudgetsを作成している部分は処理速度が速い`concat`に変更しました。

2020-12-25 19:18 UTC, toshi1127 commented on src/templates/EditStandardBudgets.tsx
> +                          newBudgets[index].budget = (event.target.value as unknown) as number;
変更できないのってなんででしたっけ？

mapでif(item === customBudget)の時に、budgetをevent.target.valueにすればいいのかなと思ったのですが

2020-12-25 19:18 UTC, toshi1127 commented on src/templates/EditStandardBudgets.tsx
> +                          newBudgets[index].budget = (event.target.value as unknown) as number;
unknown使うのもやめましょう

2020-12-26 09:05 UTC, ryo-wens commented
347b9ab

- `ColorExplanation`の`payerColorBox function`で型アサーションを使用してundefinedの型チェックを無視していましたが
   タイプガードでundefinedを許容しない形に修正しました。

2020-12-26 09:40 UTC, toshi1127 commented on src/components/budget/GroupStandardBudgets.tsx
> +                  groupStandardBudgets.map((groupBudget) => {
ここlet使いたくないのと、複数箇所で使っているのでどうにかしませんか？

2020-12-26 09:41 UTC, toshi1127 commented on src/components/home/ColorExplanation.tsx
>      let color = '';
再代入はしないようにしましょう

2020-12-26 09:42 UTC, toshi1127 commented on src/lib/constant.ts
デザインシステムっぽく管理しますか

2020-12-26 09:43 UTC, toshi1127 commented on src/reducks/budgets/selectors.ts
> +const standardBudgetsList = (state: State) => state.budgets.standard_budgets_list;
for使うのやめて、foreachなりmapで実装しましょう

2020-12-26 11:09 UTC, toshi1127 commented on src/components/home/RecentInputBody.tsx
>                    <span className="recent-input__item-font">店名: </span> {shop}
フラグメント使う必要ないような

2020-12-26 11:09 UTC, toshi1127 commented on src/templates/CustomBudgets.tsx
> +                  pathName !== 'group'
コンポーネントがpathに依存しちゃってるので、どうにかしたいです
一番上のコンポーネントから、isgroupみたいなフラグもらうなり、コンポーネントが複雑になるならを共通化するかすら考えた方が良さそうです

2020-12-26 11:15 UTC, ryo-wens commented on src/components/home/RecentInputBody.tsx
>                    <span className="recent-input__item-font">店名: </span> {shop}
店名, メモの部分にだけstyleを当てたかったのでフラグメントを使用しています。

2020-12-26 14:14 UTC, ryo-wens commented on src/reducks/budgets/selectors.ts
> +const standardBudgetsList = (state: State) => state.budgets.standard_budgets_list;
処理速度が高速なのでforで実装しました。

2020-12-27 06:07 UTC, ryo-wens commented
09e057c

分割代入の部分でletを使用していましたがconstに変更しました。

2020-12-27 06:08 UTC, merged