Add YearlyAccount template and SelectMonth SelectYear component
ryo-wens/kakeibo-front pull request #298
Opened 2020-12-30 06:43 UTC by ryo-wens

- 選択した年の会計データの表示を切り替える際に年を選択させる`SelectYear.tsx`、月を選択させる`SelectMonth.tsx`を
   追加しました。

- 年間の会計データ一覧を表示する`YearlyAccount.tsx`を追加しました。

- 年間の会計データ一覧から選択した月の会計データ編集画面の`PayOff.tsx`に遷移するようにルーティング を設定しました。

確認よろしくお願いします。

2020-12-30 11:54 UTC, toshi1127 commented on src/templates/YearlyAccount.tsx
> +  const defaultStyle = (status: string) => {
let使う必要ありますか？

2020-12-30 11:57 UTC, toshi1127 commented on src/templates/YearlyAccount.tsx
> +    if (accountStatus) {
accountStatusって一時変数に入れる必要ありますか？？
命名があれなのか、`if (accountStatus) `だけみると、nullableな値なのかな？と誤解を生みそう

2020-12-30 11:57 UTC, toshi1127 commented on src/templates/YearlyAccount.tsx
> +            {<SelectYears selectedYear={selectedYear} setSelectedYear={setSelectedYear} />}
{}使う必要ありますか？

2020-12-30 11:58 UTC, toshi1127 commented on src/templates/YearlyAccount.tsx
> +                  Number(accountStatus.month.split('月')[0]) <= 9
前も指摘しましたが、マジックナンバー使わないようにしたいです

2020-12-30 12:00 UTC, toshi1127 commented on src/templates/YearlyAccount.tsx
> +                        onClick={() =>
aタグのclick使う理由はなんですか？

2020-12-30 12:00 UTC, toshi1127 commented on src/templates/YearlyAccount.tsx
> +                  Number(accountStatus.month.split('月')[0]) <= 9
前も指摘しましたが、マジックナンバー使わないようにしたいです

2020-12-30 12:01 UTC, toshi1127 commented on src/templates/YearlyAccount.tsx
> +                  Number(accountStatus.month.split('月')[0]) <= 9
前も指摘しましたが、マジックナンバー使わないようにしたいです

2020-12-30 12:02 UTC, toshi1127 commented on src/templates/PayOff.tsx
> +  const selectYear = useLocation().pathname.split('/')[4];
pathそのものに依存させるのも良くないし、indexで指定しているのも良くないですね
（これも前から指摘していますが

2021-01-03 03:58 UTC, ryo-wens commented
2c1572e

- FAILED_FETCH_DATAにstatus codeとerror messageを追加しました。

- `fetchGroupAccount`のレスポンスのメッセージによってボタンの表示を切り替える処理を追加しました。

2021-01-03 04:00 UTC, ryo-wens commented on src/templates/YearlyAccount.tsx
> +                        onClick={() =>
編集画面にルーティング するようにclickを設定しました。

2021-01-03 04:00 UTC, ryo-wens commented on src/templates/YearlyAccount.tsx
> +    if (accountStatus) {
変数に入れない形に修正したいと思います。

2021-01-03 04:09 UTC, ryo-wens commented on src/templates/YearlyAccount.tsx
> +            {<SelectYears selectedYear={selectedYear} setSelectedYear={setSelectedYear} />}
不要でした。
削除したいと思います。

2021-01-04 16:20 UTC, ryo-wens commented
b5a3161

- WATING_FETCH_DATAをSTART_FETCH_DATAにリネームしました。

- pathの中に設定し使用していたyear, monthをquery paramsに設定し使用する形に修正しました。

- マジックナンバーを使用していた部分を変数に入れて変数を使用する形に修正しました。

2021-01-04 16:59 UTC, ryo-wens commented
ea5e1f8

- START_FETCH_DATAのtypeに代入する文字列を修正しました。

2021-01-04 17:06 UTC, neetzama requested changes
問題ないかと思います。

2021-01-04 17:11 UTC, neetzama approved these changes

2021-01-05 05:09 UTC, ryo-wens commented on src/templates/PayOff.tsx
> +  const selectYear = useLocation().pathname.split('/')[4];
変数に入れて使用する形に修正しました。

2021-01-05 05:39 UTC, merged