Modify group todo list type
ryo-wens/kakeibo-front pull request #407
Opened 2021-02-15 11:04 UTC by neetzama

- グループのTodoリストで、使用していないプロパティ、`user_id`を取り除き、型を`GroupTodoList`から`TodoList`に変更しました。

2021-02-15 14:48 UTC, ryo-wens approved these changes

2021-02-16 03:52 UTC, toshi1127 requested changes

2021-02-16 03:52 UTC, toshi1127 commented on src/containers/todo/page/monthlyTodoListArea/Items/MonthlyImplementationDateTodoListContainer.tsx
> +  const groupMonthlyImplementationTodoList = useSelector(getGroupMonthlyImplementationTodoList);
オブジェクトの形にして無理やり再代入するの辞めましょう
本質的に何も意味ないし、むしろ誤解しやすいです

2021-02-16 03:54 UTC, toshi1127 requested changes

2021-02-16 03:54 UTC, toshi1127 commented on src/containers/todo/page/monthlyTodoListArea/Items/MonthlyDueDateTodoListContainer.tsx
>        return true;
イコールか判定するような命名で代入までしているのは気になりました

2021-02-16 03:54 UTC, toshi1127 commented on src/reducks/groupTodoList/selectors.ts
> +    const { user_id, ...rest } = listItem; //eslint-disable-line
使わない変数は_にしましょう
eslintを無効化するときは特定のルールだけにしたいですね

2021-02-17 16:55 UTC, toshi1127 commented on src/reducks/groupTodoList/selectors.ts
> +  for (const item of todoList) {
reduce使うと綺麗にかけるはずですが....
一旦これでも良いと思いますー

2021-02-17 18:22 UTC, neetzama commented on src/reducks/groupTodoList/selectors.ts
> +  for (const item of todoList) {
了解です！

2021-02-17 18:22 UTC, merged