Modify the operations of budgets and group budgets
ryo-wens/kakeibo-front pull request #443
Opened 2021-03-31 14:36 UTC by ryo-wens

- standardBudgetsをcustomBudgetsに代入する処理を行なっていた`copyStandardBudgets, groupCopyStandardBudgets`
  を削除し代入の処理を`selectors`で行う形に修正しました。

- 予算の更新, 追加のボタンのdisabledの条件をstateで管理しているbudgetの合計値とselectorで取得した合計値を比較する
  形に修正しました。

2021-03-31 15:20 UTC, ryo-wens commented
d17e89b

- 不要なコメントアウトを削除しました。

2021-03-31 16:05 UTC, neetzama approved these changes

2021-04-03 09:06 UTC, ryo-wens commented
fafda14

- `budgets,groupBudgets/selector`の`getCopiedCustomBudgets`をcustomBudgetsの初期値としてstandardBudgetsの値を
   セットし表示するというReact側の責務に則した`getInitialGroupCustomBudgets`という命名に修正しました。

- budgetsのコンポーネントで管理しているbudgetsListのstateの末尾にListをつけることを統一しました。

2021-04-05 12:11 UTC, toshi1127 requested changes
セルフレビューして綺麗に書けそうなところがないか見る習慣をつけた方が良いかもです！

2021-04-05 12:11 UTC, toshi1127 commented on src/containers/budgets/AddCustomBudgetsContainer.tsx
>          if (queryMonth != null) {
queryMonthがnullの時に何もしないようですが、からの関数を渡す理由は何でしょうか？

2021-04-05 12:39 UTC, ryo-wens commented on src/containers/budgets/AddCustomBudgetsContainer.tsx
> +  const totalCustomBudget = () => {
更新ボタンのdisabledの判定を行う関数です。
関数名と処理の方法を修正したいと思います。

2021-04-05 14:56 UTC, ryo-wens commented on src/containers/budgets/AddCustomBudgetsContainer.tsx
>          if (queryMonth != null) {
インラインで書いた場合、テスト書きづらい形になってしまうのでbodyに切り出すべきでた。
修正します。

2021-04-06 17:43 UTC, ryo-wens commented
2b00225

- インラインに書いていたイベントハンドラーをbodyに切り出す形に修正しました。

- 更新ボタンのdisabledの判定を行う関数名を処理内容に応じた関数名に修正しました。

2021-04-10 08:03 UTC, merged